name: deggen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52071
title: 'Darren Eggenschwiler B.Eng. Video Producer | Tech Wizard | Cinematographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7d7d7d'
    - '#ff942c'
    - '#db1215'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
